title: Medical Image Registration
description: >-
  Learn medical image registration in a simple and practical way using python
  notebook. In this course, I try to cover the math and the theory using simple
  examples. 
template:
  repo: medical-image-registration-template
  name: medical-image-registration
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
